document.addEventListener("DOMContentLoaded", () => {
  console.log("document loaded");
  drawSpeedChart(987);
  drawAltitudeChart(9000);
  drawFlightsTable(flightsLOT);
  findAllAircrafts(flightsLOT.response);
});

function drawSpeedChart(speed) {
  var data = [
    {
      domain: { x: [0, 1], y: [0, 1] },
      value: speed,
      title: {},
      type: "indicator",
      mode: "gauge+number",
      delta: { reference: 1050 },
      gauge: { axis: { range: [null, 1050] } },
    },
  ];
  let margin = {
    b: 0,
    l: 0,
    t: 0,
    r: 0,
  };
  var layout = {
    width: 200,
    height: 120,
    margin,
    paper_bgcolor: "rgba(0,0,0,0)",
  };
  let config = {
    displayModeBar: false,
  };
  Plotly.newPlot("chart-speed", data, layout, config);
}
function drawAltitudeChart(alt) {
  var data = [
    {
      domain: { x: [0, 1], y: [0, 1] },
      value: alt,
      title: {},
      type: "indicator",
      mode: "gauge+number",
      delta: { reference: 1050 },
      gauge: { axis: { range: [null, 12000] } },
    },
  ];
  let margin = {
    b: 0,
    l: 0,
    t: 0,
    r: 0,
  };
  var layout = {
    width: 200,
    height: 120,
    margin,
    paper_bgcolor: "rgba(0,0,0,0)",
  };
  let config = {
    displayModeBar: false,
  };
  Plotly.newPlot("chart-alt", data, layout, config);
}
function drawFlightsTable(flights) {
  const table = document.getElementById("flights-table");
  const thead = document.createElement("thead");
  thead.innerHTML = "";
  thead.innerHTML = `<tr>
  <th>Flight nr</th>
  <th>From</th>
  <th>To</th>
  <th>Altitude [m]</th>
  <th>Speed [km/h]</th>
  <th>Status</th>
  </tr>`;
  table.appendChild(thead);
  const tbody = document.createElement("tbody");
  flights.response.forEach((flight) => {
    const tr = document.createElement("tr");
    tr.innerHTML = `
    <td>${flight.flight_icao}</td>
    <td>${flight.dep_iata}</td>
    <td>${flight.arr_iata}</td>
    <td>${flight.alt}</td>
    <td>${flight.speed}</td>
    <td>${flight.status}</td>
    `;
    tbody.appendChild(tr);
    tr.addEventListener("mouseenter", () => {
      const hasActive = tr.classList.contains("active");
      if (!hasActive) {
        tr.classList.add("active");
      }
    });
    tr.addEventListener("mouseleave", () => {
      const hasActive = tr.classList.contains("active");
      if (hasActive) {
        tr.classList.remove("active");
      }
    });
    tr.addEventListener("click", () => {
      console.log(flight.speed, flight.alt);
      drawSpeedChart(flight.speed);
      drawAltitudeChart(flight.alt);
    });
  });
  table.appendChild(tbody);
}
function findAllAircrafts(flights) {
  const aircrafts = [];
  flights.forEach((flight) => {
    const onList = aircrafts.includes(flight.aircraft_icao);
    if (!onList) {
      aircrafts.push(flight.aircraft_icao);
    }
  });
  console.log(aircrafts);
}
//weater
const Warsaw = {
  cloud_pct: 3,
  temp: -9,
  feels_like: -12,
  humidity: 74,
  min_temp: -10,
  max_temp: -6,
  wind_speed: 2.06,
  wind_degrees: 250,
  sunrise: 1704782566,
  sunset: 1704811340,
};
//flights LOT
let flightsLOT = {
  request: {
    lang: "en",
    currency: "USD",
    time: 1,
    id: "he5dlnkzols",
    server: "e",
    host: "airlabs.co",
    pid: 664384,
    key: {
      id: 29222,
      api_key: "2404922b-ef38-4743-a20d-93738e9e560c",
      type: "free",
      expired: "2024-01-30T23:00:00.000Z",
      registered: "2024-01-01T15:40:26.000Z",
      upgraded: null,
      limits_by_hour: 2500,
      limits_by_minute: 250,
      limits_by_month: 1000,
      limits_total: 973,
    },
    params: {
      airline_icao: "LOT",
      lang: "en",
    },
    version: 9,
    method: "flights",
    client: {
      ip: "176.221.123.8",
      geo: {
        country_code: "PL",
        country: "Poland",
        continent: "Europe",
        city: "Olsztyn",
        lat: 53.7768,
        lng: 20.4961,
        timezone: "Europe/Warsaw",
      },
      connection: {
        type: "cable/dsl",
        isp_code: 21021,
        isp_name: "Multimedia Polska S.A.",
      },
      device: {},
      agent: {},
      karma: {
        is_blocked: false,
        is_crawler: false,
        is_bot: false,
        is_friend: false,
        is_regular: true,
      },
    },
  },
  response: [
    {
      hex: "489786",
      reg_number: "SP-LDF",
      flag: "PL",
      lat: 51.025256,
      lng: 15.580902,
      alt: 7505,
      dir: 248,
      speed: 679,
      v_speed: -11.7,
      squawk: "1000",
      flight_number: "5MZ",
      flight_icao: "LOT5MZ",
      flight_iata: "LO521",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LKPR",
      arr_iata: "PRG",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E170",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "489789",
      reg_number: "SP-LDI",
      flag: "PL",
      lat: 49.051721,
      lng: 19.996996,
      alt: 10355,
      dir: 188.2,
      speed: 827,
      v_speed: -4.6,
      squawk: "1000",
      flight_number: "537",
      flight_icao: "LOT537",
      flight_iata: "LO537",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LHBP",
      arr_iata: "BUD",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E170",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE02",
      reg_number: "SP-LRC",
      flag: "PL",
      lat: 46.458342,
      lng: 24.628258,
      alt: 11887,
      dir: 137,
      speed: 968,
      v_speed: 0.7,
      squawk: "4513",
      flight_number: "6189",
      flight_icao: "LOT6189",
      flight_iata: "LO6189",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "VVPQ",
      arr_iata: "PQC",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B788",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AF02",
      reg_number: "SP-LVC",
      flag: "PL",
      lat: 45.480978,
      lng: 6.148257,
      alt: 11277,
      dir: 198,
      speed: 775,
      v_speed: 0,
      squawk: "3551",
      flight_number: "437",
      flight_icao: "LOT437",
      flight_iata: "LO437",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LEBL",
      arr_iata: "BCN",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B38M",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AF03",
      reg_number: "SP-LVD",
      flag: "PL",
      lat: 52.371826,
      lng: 13.299735,
      alt: 10972,
      dir: 269.2,
      speed: 766,
      v_speed: 0,
      squawk: "0601",
      flight_number: "279",
      flight_icao: "LOT279",
      flight_iata: "LO279",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "EGLL",
      arr_iata: "LHR",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B38M",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE25",
      reg_number: "SP-LSF",
      flag: "PL",
      lat: 49.434799,
      lng: 21.605654,
      alt: 10690,
      dir: 168,
      speed: 946,
      v_speed: 1.6,
      squawk: "5573",
      flight_number: "6281",
      flight_icao: "LOT6281",
      flight_iata: "LO6281",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "VTSG",
      arr_iata: "KBV",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B789",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE83",
      reg_number: "SP-LWD",
      flag: "PL",
      lat: 46.256378,
      lng: 25.220724,
      alt: 10668,
      dir: 130,
      speed: 885,
      v_speed: -0.3,
      squawk: "4514",
      flight_number: "727",
      flight_icao: "LOT727",
      flight_iata: "LO727",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "UDYZ",
      arr_iata: "EVN",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B738",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48ADA6",
      reg_number: "SP-LNG",
      flag: "PL",
      lat: 51.578343,
      lng: 20.213547,
      alt: 5783,
      dir: 221,
      speed: 632,
      v_speed: 8.8,
      squawk: "1000",
      flight_number: "34P",
      flight_icao: "LOT34P",
      flight_iata: "LO343",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LFMN",
      arr_iata: "NCE",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E195",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48978A",
      reg_number: "SP-LDK",
      flag: "PL",
      lat: 51.984791,
      lng: 21.132202,
      alt: 1196,
      dir: 298.7,
      speed: 354,
      v_speed: -5.2,
      squawk: "5614",
      flight_number: "798",
      flight_icao: "LOT798",
      flight_iata: "LO798",
      dep_icao: "EYVI",
      dep_iata: "VNO",
      arr_icao: "EPWA",
      arr_iata: "WAW",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E170",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AD10",
      reg_number: "SP-LIR",
      flag: "PL",
      lat: 47.933908,
      lng: 16.66795,
      alt: 1181,
      dir: 314,
      speed: 374,
      v_speed: -2.6,
      squawk: "1000",
      flight_number: "221",
      flight_icao: "LOT221",
      flight_iata: "LO221",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LOWW",
      arr_iata: "VIE",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E75S",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE00",
      reg_number: "SP-LRA",
      flag: "PL",
      lat: 46.609776,
      lng: 20.472885,
      alt: 7162,
      dir: 114.1,
      speed: 929,
      v_speed: 7.5,
      squawk: "4245",
      flight_number: "2001",
      flight_icao: "LOT2001",
      flight_iata: "LO2001",
      dep_icao: "LHBP",
      dep_iata: "BUD",
      arr_icao: "RKSI",
      arr_iata: "ICN",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B788",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AF07",
      reg_number: "SP-LVH",
      flag: "PL",
      lat: 28.405518,
      lng: 49.160913,
      alt: 8534,
      dir: 326,
      speed: 775,
      v_speed: 0,
      squawk: "0521",
      flight_number: "122",
      flight_icao: "LOT122",
      flight_iata: "LO122",
      dep_icao: "OMDB",
      dep_iata: "DXB",
      arr_icao: "EPWA",
      arr_iata: "WAW",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B38M",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AD84",
      reg_number: "SP-LME",
      flag: "PL",
      lat: 55.969986,
      lng: 24.191312,
      alt: 5189,
      dir: 349,
      speed: 642,
      v_speed: -13.3,
      squawk: "3710",
      flight_number: "7RM",
      flight_icao: "LOT7RM",
      flight_iata: "LO781",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "EVRA",
      arr_iata: "RIX",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E190",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AD83",
      reg_number: "SP-LMD",
      flag: "PL",
      lat: 52.178661,
      lng: 20.963326,
      alt: 0,
      dir: 244,
      speed: 2,
      v_speed: 0,
      squawk: "1000",
      flight_number: "2WP",
      flight_icao: "LOT2WP",
      flight_iata: "LO253",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "ELLX",
      arr_iata: "LUX",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E190",
      updated: 1704296478,
      status: "scheduled",
      type: "adsb",
    },
    {
      hex: "48AF09",
      reg_number: "SP-LVK",
      flag: "PL",
      lat: 52.165604,
      lng: 20.974236,
      alt: 0,
      dir: 115.3,
      speed: 43,
      v_speed: 0,
      squawk: "1000",
      flight_number: "5KT",
      flight_icao: "LOT5KT",
      flight_iata: "LO303",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LIRF",
      arr_iata: "FCO",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B38M",
      updated: 1704296478,
      status: "scheduled",
      type: "adsb",
    },
    {
      hex: "48ADA3",
      reg_number: "SP-LND",
      flag: "PL",
      lat: 41.189575,
      lng: 28.821411,
      alt: 1158,
      dir: 125.3,
      speed: 442,
      v_speed: 12.7,
      squawk: "5327",
      flight_number: "136",
      flight_icao: "LOT136",
      flight_iata: "LO136",
      dep_icao: "LTFM",
      dep_iata: "IST",
      arr_icao: "EPWA",
      arr_iata: "WAW",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E195",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE20",
      reg_number: "SP-LSA",
      flag: "PL",
      lat: 28.65381,
      lng: 61.177,
      alt: 11582,
      dir: 320,
      speed: 724,
      v_speed: -0.3,
      flight_number: "6280",
      flight_icao: "LOT6280",
      flight_iata: "LO6280",
      dep_icao: "VTBS",
      dep_iata: "BKK",
      arr_icao: "EPWA",
      arr_iata: "WAW",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B789",
      updated: 1704296414,
      status: "en-route",
      type: "adsb",
    },
    {
      hex: "48AE85",
      reg_number: "SP-LWF",
      flag: "PL",
      lat: 52.173763,
      lng: 20.970421,
      alt: 0,
      dir: 241,
      speed: 0,
      v_speed: 0,
      squawk: "2000",
      flight_number: "335",
      flight_icao: "LOT335",
      flight_iata: "LO335",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LFPG",
      arr_iata: "CDG",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B738",
      updated: 1704296477,
      status: "landed",
      type: "adsb",
    },
    {
      hex: "48ADA7",
      reg_number: "SP-LNH",
      flag: "PL",
      lat: 46.93257,
      lng: 28.92182,
      alt: 0,
      dir: 90,
      speed: 18,
      v_speed: 0,
      flight_number: "515",
      flight_icao: "LOT515",
      flight_iata: "LO515",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "LUKK",
      arr_iata: "KIV",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "E195",
      updated: 1704296412,
      status: "landed",
      type: "adsb",
    },
    {
      hex: "48AE03",
      reg_number: "SP-LRD",
      flag: "PL",
      lat: 61.1,
      lng: -29.28,
      alt: 11582,
      dir: 254,
      speed: 900,
      v_speed: -0.3,
      flight_number: "29",
      flight_icao: "LOT29",
      flight_iata: "LO29",
      dep_icao: "EPWA",
      dep_iata: "WAW",
      arr_icao: "KMIA",
      arr_iata: "MIA",
      airline_icao: "LOT",
      airline_iata: "LO",
      aircraft_icao: "B788",
      updated: 1704296478,
      status: "en-route",
      type: "adsb",
    },
  ],
  terms:
    "Unauthorized access is prohibited and punishable by law. \nReselling data 'As Is' without AirLabs.Co permission is strictly prohibited. \nFull terms on https://airlabs.co/. \nContact us info@airlabs.co",
};
